AWSTemplateFormatVersion: '2010-09-09'
Description: 'MatchTal-AI: Single EC2 instance with Docker pre-installed.'

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.

  AllowedIP:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Mappings:
  # Amazon Linux 2023 AMI IDs (us-east-1, us-west-2, etc.)
  # These change frequently. To keep it robust, we should arguably use SSM Parameters, 
  # but for simplicity in this template we'll use a specific recent AL2023 ID for us-east-1.
  # Better approach: Use the Latest Ami Id from SSM in the Resources section.
  RegionMap: 
    us-east-1: 
      AMI: ami-0230bd60aa48260c6 # Amazon Linux 2023 AMI 2023.6.20250211.0 x86_64 HVM kernel-6.1

Resources:
  MatchTalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedIP
        - IpProtocol: tcp
          FromPort: 8002
          ToPort: 8002
          CidrIp: 0.0.0.0/0
  
  MatchTalInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups: 
        - !Ref MatchTalSecurityGroup
      KeyName: !Ref KeyName
      # Using a dynamic SSM parameter to get the latest Amazon Linux 2023 AMI
      ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y docker
          service docker start
          usermod -a -G docker ec2-user
          systemctl enable docker
      Tags:
        - Key: Name
          Value: MatchTal-Profile-Service

Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref MatchTalInstance
  IPAddress:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt MatchTalInstance.PublicIp
